import test, { expect } from "@playwright/test"

test('Edit Lead leaftap',async({page})=>{

await page.goto('http://leaftaps.com/opentaps/control/main')
await page.getByRole('textbox',{name:'Username'}).fill('Demosalesmanager')
await page.getByRole('textbox',{name:'Password'}).fill('crmsfa')
await page.getByRole('button',{name:'Login'}).click()
await page.waitForTimeout(5000)
await page.getByRole('link',{name:'CRM/SFA'}).click()
await page.getByRole('link',{name:'Leads'}).click()
await page.getByRole('link',{name:'Find Leads'}).click()
await page.getByRole('textbox',{name:'First name:'}).fill("Laxmi")
await page.getByRole('button',{name:'Find Leads'}).click()
await page.locator(`(//div[@class='x-grid3-cell-inner x-grid3-col-partyId']/a)[1]`).click()
await page.waitForTimeout(5000)
await page.getByRole('link',{name:'Edit'}).click()
await page.locator(`//input[@id='updateLeadForm_companyName']`).clear()
expect(page.locator(`//input[@id='updateLeadForm_companyName']`)).toBeEditable()
await page.locator(`//input[@id='updateLeadForm_companyName']`).fill("SAI Enterprise")
await page.locator(`//input[@id='updateLeadForm_annualRevenue']`).clear()
expect(page.locator(`//input[@id='updateLeadForm_annualRevenue']`)).toBeEditable()
await page.locator(`//input[@id='updateLeadForm_annualRevenue']`).fill('56700000')
await page.locator(`//input[@id='updateLeadForm_departmentName']`).clear()
expect(page.locator(`//input[@id='updateLeadForm_departmentName']`)).toBeEditable()
await page.locator(`//input[@id='updateLeadForm_departmentName']`).fill('R&D Department')
await page.locator(`//textarea[@id='updateLeadForm_description']`).clear()
expect(page.locator(`//textarea[@id='updateLeadForm_description']`)).toBeEditable()
await page.locator(`//textarea[@id='updateLeadForm_description']`).fill('This is the Sai Enterprise company head office at Bangalore')
await page.getByRole('button',{name:'Update'}).click()

const compNameExpected=await page.locator(`//span[@id='viewLead_companyName_sp']`).innerText()
const annualRevenueExpected = await page.locator(`//span[@id='viewLead_annualRevenue_sp']`).innerText()
const descriptionExpected = await page.locator(`//span[@id='viewLead_description_sp']`).innerText()
const departmentExpected = await page.locator(`//span[@id='viewLead_departmentName_sp']`).innerText()

expect(compNameExpected).toContain('SAI Enterprise')
expect(annualRevenueExpected).toContain('$56,700,000.00')
expect(descriptionExpected).toBe('This is the Sai Enterprise company head office at Bangalore')
expect(departmentExpected).toBe('R&D Department')
await page.waitForTimeout(5000)
})